# Generated by Django 3.0.4 on 2020-09-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200912_1529'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorLocationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.Creator')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Location')),
            ],
        ),
    ]
