# Generated by Django 3.2.10 on 2022-05-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationnumber',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.location'),
        ),
        migrations.AddField(
            model_name='creator',
            name='is_alias_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creators.creator'),
        ),
        migrations.AddField(
            model_name='creatorlocationnumber',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator'),
        ),
    ]
