# Generated by Django 3.1.1 on 2020-12-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200912_1529'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('letter', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('auto_name', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.location')),
            ],
        ),
        migrations.RemoveField(
            model_name='creator',
            name='identifying_code',
        ),
        migrations.AddField(
            model_name='creator',
            name='mark_for_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creator',
            name='given_names',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='creator',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreatorLocationNumber',
            fields=[
                ('locationnumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creators.locationnumber')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
            ],
            bases=('creators.locationnumber',),
        ),
    ]
