# Generated by Django 3.0.4 on 2020-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_auto_20200913_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
