# Generated by Django 4.2.15 on 2024-08-27 17:13

from django.db import migrations
from django.db.migrations import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_remove_creatorlocationnumber_locationnumber_ptr_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='locationnumber',
            name='auto_name',
        ),
        migrations.RemoveField(
            model_name='locationnumber',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='locationnumber',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locationnumber',
            name='name',
        ),
        migrations.RemoveField(
            model_name='locationnumber',
            name='number',
        )
    ]
