# Generated by Django 4.2.15 on 2024-08-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_remove_locationnumber_auto_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationNumber',
        ),
    ]
