# Generated by Django 3.0.4 on 2020-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_auto_20200914_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='mark_for_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creator',
            name='given_names',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
