# Generated by Django 3.0.4 on 2020-09-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200912_1529'),
        ('series', '0003_series_location'),
        ('creators', '0005_auto_20200914_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorlocationnumber',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AlterField(
            model_name='creatorlocationnumber',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.Location'),
        ),
    ]
