# Generated by Django 3.0.3 on 2020-10-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0006_auto_20200923_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorlocationnumber',
            name='series',
        ),
        migrations.AlterField(
            model_name='creatorlocationnumber',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creators.Creator'),
        ),
    ]
