# Generated by Django 3.0.4 on 2020-04-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0003_itemstate_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventarisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Location')),
            ],
        ),
    ]
