# Generated by Django 3.0.4 on 2020-07-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarisation', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarisation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Location'),
        ),
    ]
