# Generated by Django 3.0.4 on 2020-08-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0005_auto_20200803_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(blank=True, max_length=64)),
                ('book_code_sortable', models.CharField(blank=True, max_length=128)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
