# Generated by Django 3.0.4 on 2020-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recode',
            name='book_code_extension',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
