# Generated by Django 5.2.5 on 2025-10-14 16:25

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0001_initial'),
        ('works', '0003_uppercase_existing_sortable_book_codes'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='recode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['book_code_sortable'], name='search_wordmatch_type_788b882f'),
        ),
    ]
