# Generated by Django 5.2.5 on 2025-10-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='book_code_extension',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
