# Generated by Django 5.2.3 on 2025-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0002_alter_recode_book_code_sortable'),
        ('works', '0005_alter_item_book_code_sortable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='book_code_sortable',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='recode',
            index=models.Index(fields=['book_code_sortable'], name='search_wordmatch_type_788b882f'),
        ),
    ]
