# Generated by Django 5.2.3 on 2025-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0002_recode_search_wordmatch_type_788b882f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recode',
            name='book_code_extension',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
