# Generated by Django 5.2.3 on 2025-10-02 15:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0003_alter_recode_book_code_sortable_and_more'),
        ('works', '0005_alter_item_book_code_sortable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recode',
            name='search_wordmatch_type_788b882f',
        ),
        migrations.AddIndex(
            model_name='recode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['book_code_sortable'], name='search_wordmatch_type_788b882f'),
        ),
    ]
