# Generated by Django 5.2.3 on 2025-11-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recode', '0003_alter_recode_book_code_extension'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recode',
            new_name='recode_recode_book_code',
            old_name='search_wordmatch_type_788b882f',
        ),
    ]
