# Generated by Django 3.2.10 on 2022-01-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0010_auto_20211002_1144'),
        ('lendings', '0003_auto_20200912_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('return_date', models.DateTimeField()),
                ('paid_on_date', models.DateTimeField(null=True)),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lendings.lending')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
