# Generated by Django 3.0.4 on 2020-09-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200912_1529'),
        ('book_code_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttercoderange',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.Location'),
        ),
    ]
