# Generated by Django 4.2.15 on 2024-08-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_rename_datetime_itemstate_date_time'),
        ('book_code_generation', '0001_initial'),
        ('creators', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCutterCodeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_name', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
                ('letter', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL("""
        INSERT INTO book_code_generation_locationcuttercoderange
             ("id", "number", "letter", "name", "auto_name","location_id")
        SELECT
            "id", "number", "letter", "name", "auto_name","location_id"
         FROM creators_locationnumber;
        """)
    ]
