# Generated by Django 3.0.3 on 2020-10-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200912_1529'),
        ('book_code_generation', '0003_remove_cuttercoderange_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttercoderange',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='works.Location'),
        ),
    ]
