# Generated by Django 3.2.10 on 2022-05-02 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lended_on', models.DateField()),
                ('times_extended', models.IntegerField(default=0)),
                ('last_extended', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('handed_in', models.BooleanField()),
                ('handed_in_on', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('last_mailed', models.DateTimeField(default='1900-01-01')),
                ('mailed_for_late', models.BooleanField(default=False)),
                ('handed_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handed_in', to='members.member')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.item')),
                ('lended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lended_out', to='members.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
            options={
                'permissions': [('extend', 'Can extend lending'), ('extend_with_fine', 'Extend book even though it has a fine'), ('return', 'Return book')],
            },
        ),
    ]
