# Generated by Django 3.0.3 on 2020-02-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lending',
            name='handed_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handed_in', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='handed_in_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lending',
            name='lended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lended_out', to='members.Member'),
        ),
    ]
