# Generated by Django 3.0.4 on 2020-04-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lending',
            options={'permissions': [('extend', 'Can extend lending'), ('extend_with_fine', 'Extend book even though it has a fine'), ('return', 'Return book')]},
        ),
    ]
