# Generated by Django 3.0.4 on 2020-08-06 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='last_mailed',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 7, 23, 3, 917899)),
        ),
    ]
