# Generated by Django 3.0.4 on 2020-08-03 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='last_mailed',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 15, 30, 18, 492491)),
        ),
        migrations.AddField(
            model_name='lending',
            name='mailed_for_late',
            field=models.BooleanField(default=False),
        ),
    ]
