# Generated by Django 3.0.4 on 2020-08-04 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
