# Generated by Django 3.0.4 on 2020-09-12 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0002_auto_20200819_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='last_mailed',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
