# Generated by Django 3.0.4 on 2020-08-03 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0002_auto_20200803_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='last_mailed',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 18, 18, 9, 734428)),
        ),
    ]
