# Generated by Django 3.0.4 on 2020-08-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0003_auto_20200806_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='last_mailed',
            field=models.DateTimeField(default='2020-01-01'),
        ),
    ]
