# Generated by Django 3.2.10 on 2022-03-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0003_auto_20200912_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
