# Generated by Django 3.0.4 on 2020-08-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lendings', '0003_auto_20200803_1818'),
        ('lendings', '0002_lending_start_date'),
    ]

    operations = [
    ]
