LENDING_LIST = 'lendings.list'
LENDING_VIEW = 'lendings.view'
LENDING_NEW_WORK = 'lendings.new.work'
LENDING_NEW_MEMBER = 'lendings.new.member'

LENDING_FINALIZE = 'lendings.finalize'
LENDING_RETURNBOOK = 'lendings.returnbook'
LENDING_GET_FINE = 'lendings.getfine'
LENDING_EXTEND = 'lendings.extend'
LENDING_MY_LENDINGS = 'lendings.me'
LENDING_FAILED = 'lendings.failed'
