LENDING_LIST = 'lendings.list'
LENDING_VIEW = 'lendings.view'
LENDING_NEW_WORK = 'lendings.new.work'
LENDING_NEW_MEMBER = 'lendings.new.member'

LENDING_FINALIZE = 'lendings.finalize'
LENDING_RETURNBOOK = 'lendings.returnbook'
LENDING_GET_FINE = 'lendings.getfine'
LENDING_EXTEND = 'lendings.extend'
LENDING_MY_LENDINGS = 'lendings.me'
LENDING_FAILED = 'lendings.failed'

RESERVE_LIST = 'lendings.reserve.list'
RESERVE_ITEM = 'lendings.reserve.item'
RESERVE_MEMBER = 'lendings.reserve.member'
RESERVE_FINALIZE = 'lendings.reserve.finalize'
RESERVE_FAILED = 'lendings.reserve_failed'
RESERVE_LEND = 'lendings.reserve_lend'
