# Generated by Django 3.2.10 on 2022-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('skipped_for_fine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LendingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_is_active', models.BooleanField(default=False)),
                ('term', models.IntegerField()),
                ('borrow_money', models.IntegerField()),
                ('fine_amount', models.IntegerField()),
                ('max_fine', models.IntegerField()),
                ('max_count', models.IntegerField()),
                ('extend_count', models.IntegerField()),
            ],
        ),
    ]
