# Generated by Django 3.0.4 on 2020-04-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('skipped_for_fine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LendingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_for_inactive', models.IntegerField()),
                ('term_for_active', models.IntegerField()),
                ('hand_in_days', models.IntegerField(default=1)),
                ('borrow_money_inactive', models.IntegerField()),
                ('borrow_money_active', models.IntegerField()),
                ('fine_amount', models.IntegerField()),
                ('max_fine', models.IntegerField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.ItemType')),
            ],
        ),
    ]
