# Generated by Django 3.0.4 on 2020-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_lendingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingsettings',
            name='fine_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingsettings',
            name='max_fine',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
