# Generated by Django 3.0.4 on 2020-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_lendingsettings_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingsettings',
            name='max_count_inactive',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
