# Generated by Django 3.0.4 on 2020-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_lendingsettings_max_count_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingsettings',
            name='max_count_active',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
