# Generated by Django 3.2.10 on 2022-03-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20220302_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendingsettings',
            name='hand_in_days',
        ),
    ]
