# Generated by Django 3.0.4 on 2020-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_lendingsettings_max_count_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingsettings',
            name='extend_count_active',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingsettings',
            name='extend_count_inactive',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
