# Generated by Django 3.0.4 on 2020-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='custom_header',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
