# Generated by Django 3.2.13 on 2022-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
