# Generated by Django 3.2.13 on 2022-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0002_externalupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpage',
            name='custom_header',
        ),
        migrations.AddField(
            model_name='publicpage',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
