# Generated by Django 3.2.13 on 2022-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0003_auto_20220923_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='only_for_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
