# Generated by Django 3.2.13 on 2022-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('public_pages', '0004_publicpage_only_for_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='limited_to_committees',
            field=models.ManyToManyField(to='members.Committee'),
        ),
    ]
