# Generated by Django 3.2.13 on 2022-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0005_publicpage_limited_to_committees'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='only_for_current_members',
            field=models.BooleanField(default=False),
        ),
    ]
