# Generated by Django 3.2.13 on 2022-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('public_pages', '0006_publicpage_only_for_current_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpage',
            name='limited_to_committees',
            field=models.ManyToManyField(blank=True, to='members.Committee'),
        ),
    ]
