# Generated by Django 3.2.22 on 2024-02-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0008_alter_fileupload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalUpload',
        ),
    ]
