# Generated by Django 5.2.3 on 2025-08-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0009_delete_externalupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='name',
        ),
    ]
