# Generated by Django 5.2.3 on 2025-08-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0010_remove_fileupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(unique=True, upload_to='.'),
        ),
    ]
