# Generated by Django 5.2.3 on 2025-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_pages', '0011_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpagegroup',
            name='publicly_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
