RESERVE_LIST = 'lendings.reserve.list'
RESERVE_ITEM = 'lendings.reserve.item'
RESERVE_MEMBER = 'lendings.reserve.member'
RESERVE_FINALIZE = 'lendings.reserve.finalize'
RESERVE_FAILED = 'lendings.reserve_failed'
RESERVE_LEND = 'lendings.reserve_lend'
RESERVE_DELETE = 'lendings.reserve_delete'
