# Generated by Django 4.2.15 on 2024-09-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('object_as_json', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('next_datetime', models.DateTimeField(auto_now_add=True)),
                ('every', models.IntegerField(default=0)),
            ],
        ),
    ]
