# Generated by Django 4.2.15 on 2024-09-22 20:57

from django.db import migrations

from lendings.tasks import LateMails
from reservations.tasks import ReservationCancel
from tasks.models import Task


def add_default_tasks(*args):
    Task.objects.create(task_name="reservation_cancel",task_object=ReservationCancel(),every=120)
    Task.objects.create(task_name="lendings_late_mails",task_object=LateMails(),every=120)

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_default_tasks
        ),
    ]
