# Generated by Django 4.2.15 on 2024-09-22 20:57

from django.db import migrations

from lendings.tasks import LateMails
from public_pages.tasks import SyncUploads
from reservations.tasks import ReservationCancel
from tasks.models import Task, CleanupOldHandledTasks


def add_fileupload_cron_task(*args):
    Task.objects.create(task_name="file_upload_sync", task_object=SyncUploads(), repeats_every_minutes=1)


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_data_migration'),
    ]

    operations = [
        migrations.RunPython(
            add_fileupload_cron_task
        ),
    ]
