# Generated by Django 3.0.3 on 2020-04-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('display_number', models.CharField(max_length=255)),
                ('old_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('seriesnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='series.SeriesNode')),
                ('language', models.CharField(max_length=64)),
                ('article', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(blank=True, max_length=64, null=True)),
                ('original_article', models.CharField(blank=True, max_length=64, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('is_translated', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('series.seriesnode', models.Model),
        ),
        migrations.CreateModel(
            name='WorkInSeries',
            fields=[
                ('seriesnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='series.SeriesNode')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Work')),
            ],
            bases=('series.seriesnode',),
        ),
        migrations.AddField(
            model_name='seriesnode',
            name='part_of_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part', to='series.Series'),
        ),
        migrations.CreateModel(
            name='CreatorToSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Creator')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.CreatorRole')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='series.Series')),
            ],
        ),
    ]
