# Generated by Django 5.2.3 on 2025-11-05 07:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('works', '0004_workrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(blank=True, max_length=64)),
                ('book_code_sortable', models.CharField(blank=True, max_length=128)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.work')),
            ],
            options={
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['book_code_sortable'], name='series_workseries_book_code')],
            },
        ),
    ]
