# Generated by Django 3.0.3 on 2020-02-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_remove_creatortowork_old_id'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorToSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Creator')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.CreatorRole')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='series.Series')),
            ],
        ),
    ]
