# Generated by Django 5.2.3 on 2025-11-10 18:02

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('works', '0005_alter_workinpublication_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(blank=True, max_length=64)),
                ('book_code_sortable', models.CharField(blank=True, max_length=128)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
            options={
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['book_code_sortable'], name='series_seriesv2_book_code')],
            },
        ),
        migrations.AddField(
            model_name='seriesv2',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='works.location'),
        ),
        migrations.AddField(
            model_name='seriesv2',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='creators.locationnumber'),
        ),
        migrations.AlterField(
            model_name='seriesv2',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
