# Generated by Django 3.0.3 on 2020-04-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesnode',
            name='article',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='is_translated',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='language',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='original_article',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='original_subtitle',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='seriesnode',
            name='title',
        ),
        migrations.AddField(
            model_name='series',
            name='article',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='is_translated',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='original_article',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='original_language',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='original_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
