# Generated by Django 5.1.1 on 2025-05-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='search_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
