# Generated by Django 5.2.5 on 2025-10-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('works', '0003_uppercase_existing_sortable_book_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSeries',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.work')),
            ],
            options={
                'abstract': False,
            },
            bases=('works.work',),
        ),
    ]
