# Generated by Django 5.1.4 on 2025-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='searchmake_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
