# Generated by Django 3.0.3 on 2020-02-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesnode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
