# Generated by Django 3.0.4 on 2020-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='book_code',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='code_extension',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='workinseries',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
