# Generated by Django 4.2.15 on 2024-08-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_code_generation', '0002_locationcuttercoderange'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='book_code_generation.locationcuttercoderange'),
        ),
    ]
