# Generated by Django 3.0.4 on 2020-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesnode',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
