# Generated by Django 3.0.4 on 2020-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatortoseries',
            name='number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='seriesnode',
            name='display_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seriesnode',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
