# Generated by Django 5.1.4 on 2025-03-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_searchmake_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='searchmake_words',
            new_name='search_words',
        ),
    ]
