# Generated by Django 5.2.3 on 2025-11-04 20:11
from datetime import timedelta

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.core.paginator import Paginator
from django.db import migrations, models, connection

from search.models import UpdateWorks
from tasks.models import Task
from utils.time import get_now
from works.models import Work


def data_migrate(apps, schema_editor):
    with connection.cursor() as cursor:
        worksQ = """
        INSERT INTO works_work (
            language,
            article,
            title,
            sub_title,
            original_language,
            original_article,
            original_title,
            original_subtitle,
            is_translated,
            date_added,
            sorting,
            comment,
            internal_comment,
            hidden,
            listed_author,
            based_on_series_id
        ) SELECT
            language,
            article,
            title,
            sub_title,
            original_language,
            original_article,
            original_title,
            original_subtitle,
            is_translated,
            '2000-01-01',
            'TITLE',
            '',
            seriesnode_ptr_id::text,
            false,
            'ZZZZZZZZ',
            seriesnode_ptr_id
        FROM series_series ON CONFLICT DO NOTHING RETURNING internal_comment::int, id
        """
        cursor.execute(worksQ, [])

        query2 = """
        INSERT INTO series_seriesv2
        (
            book_code,
            book_code_sortable,
            work_id,
            location_id,
            location_code_id
        ) SELECT
            series_series.book_code,
            series_series.book_code_sortable,
            works_work.id,
            series_series.location_id,
            series_series.location_code_id
            FROM series_series
        LEFT JOIN works_work ON series_series.seriesnode_ptr_id = works_work.based_on_series_id
        """
        cursor.execute(query2, [])

        query_creators = """
        INSERT INTO works_creatortowork
        (
            number,
            creator_id,
            role_id,
            work_id
        ) SELECT
            series_creatortoseries.number,
            series_creatortoseries.creator_id,
            series_creatortoseries.role_id,
            works_work.id
        FROM series_creatortoseries
        JOIN works_work ON works_work.based_on_series_id = series_creatortoseries.series_id
        """
        cursor.execute(query_creators, [])

        query_relations = """
        INSERT INTO works_workrelation
        (
            relation_index,
            relation_index_label,
            relation_kind,
            from_work_id,
            to_work_id
        )
        SELECT
            coalesce(number, -6),
            display_number,
             CASE
                WHEN coalesce(series_workinseries.is_primary, true) = TRUE THEN 2
                ELSE 3
            END,
            coalesce(from_work.id, wwork.id),
            to_work.id
        FROM series_seriesnode
            LEFT JOIN series_workinseries ON series_seriesnode.id = series_workinseries.seriesnode_ptr_id
            LEFT JOIN works_work as from_work ON series_seriesnode.id = from_work.based_on_series_id
            LEFT JOIN works_work as wwork ON series_workinseries.work_id = wwork.id
            JOIN works_work as to_work ON series_seriesnode.part_of_series_id = to_work.based_on_series_id
        """
        cursor.execute(query_relations, [])


def start_series_data_update(apps, schema_editor):
    works = Work.objects.filter(seriesv2__isnull=False).order_by("id")
    time = get_now()
    c = 0
    for wks in Paginator(works, 100):

        print(c)
        c += 1
        Task.objects.create(next_datetime=time, task_name="migrate_series_data_update",
                            task_object=UpdateWorks(list(wks.object_list)))
        time += timedelta(milliseconds=200)


class Migration(migrations.Migration):
    dependencies = [
        ('series', '0002_seriesv2'),
        ('works', '0010_work_based_on_series'),
        ("tasks", "0003_add_file_upload_cron_task")
    ]

    operations = [
        migrations.RunPython(data_migrate),
        migrations.RunPython(start_series_data_update),
    ]
