# Generated by Django 5.2.3 on 2025-11-04 20:11

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models, connection


def data_migrate(apps, schema_editor):
    with connection.cursor() as cursor:
        worksQ = """
        INSERT INTO works_work (
language,
article,
title,
sub_title,
original_language,
original_article,
original_title,
original_subtitle,
is_translated,
date_added,
sorting,
comment,
internal_comment,
hidden,
listed_author,
based_on_series_id
        ) SELECT 
language,
article,
title,
sub_title,
original_language,
original_article,
original_title,
original_subtitle,
is_translated,
'2000-01-01',
'TITLE',
'',
seriesnode_ptr_id::text,
false,
'ZZZZZZZZ',
seriesnode_ptr_id
         FROM series_series ON CONFLICT DO NOTHING RETURNING internal_comment::int, id
        """
        cursor.execute(worksQ, [])
        query2 = """
        INSERT INTO series_workseries 
        (
            book_code,
            book_code_sortable,
            work_id
        ) SELECT 
        series_series.book_code,
        series_series.book_code_sortable,
        works_work.id
        FROM series_series
        LEFT JOIN works_work ON series_series.seriesnode_ptr_id = works_work.based_on_series_id
        """
        cursor.execute(query2, [])

        query_creators = """
        INSERT INTO works_creatortowork
        (
        number,
        creator_id,
        role_id,
        work_id
        ) SELECT 
        series_creatortoseries.number,
        series_creatortoseries.creator_id,
        series_creatortoseries.role_id,
        works_work.id
        FROM series_creatortoseries
        JOIN works_work ON works_work.based_on_series_id = series_creatortoseries.series_id
        """
        cursor.execute(query_creators, [])


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_workseries'),
        ('works', '0005_work_based_on_series'),
    ]

    operations = [
        migrations.RunPython(data_migrate),
    ]
