# Generated by Django 5.2.5 on 2025-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_newseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='newseries',
            name='book_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newseries',
            name='book_code_sortable',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
