# Generated by Django 3.0.3 on 2020-02-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_seriesnode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesnode',
            name='part_of_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part', to='series.Series'),
        ),
    ]
