# Generated by Django 3.0.4 on 2020-09-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200912_1529'),
        ('series', '0002_auto_20200912_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='works.Location'),
        ),
    ]
