# Generated by Django 3.0.4 on 2020-07-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20200730_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='code_extension',
            new_name='book_code_extension',
        ),
    ]
