# Generated by Django 3.0.4 on 2020-05-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20200416_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesnode',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
