# Generated by Django 5.2.5 on 2025-10-15 14:06
import datetime
import time

from django.db import migrations, models

from series.models import NewSeries, Series


def data_migrate(apps, schema_editor):
    for ser in Series.objects.all():
        NewSeries.objects.create(
            title= ser.title,
            article= ser.article,
            language= ser.language,
            sub_title= ser.sub_title,

            original_title=ser.original_title,
            original_subtitle=ser.original_subtitle,
            original_language=ser.original_language,
            original_article=ser.original_article,

            is_translated=ser.is_translated,

            book_code=ser.book_code,
            book_code_sortable=ser.book_code_sortable,
            date_added=datetime.date.today(),
            hidden=True,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_newseries_book_code_newseries_book_code_sortable'),
    ]

    operations = [
        migrations.RunPython(
            data_migrate,
        ),
    ]
