# Generated by Django 5.2.3 on 2025-11-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_workseries_datamigrate'),
        ('works', '0011_remove_work_based_on_series'),
    ]

    operations = [

        migrations.DeleteModel(
            name='CreatorToSeries',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='SeriesNode',
        ),
        migrations.DeleteModel(
            name='WorkInSeries',
        ),
    ]
