# Generated by Django 3.1.1 on 2020-12-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_auto_20201203_1856'),
        ('series', '0003_series_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='location_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creators.locationnumber'),
        ),
    ]
