# Generated by Django 3.0.4 on 2020-07-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20200730_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='book_code_extension',
        ),
    ]
