# Generated by Django 3.0.4 on 2020-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200510_1322'),
        ('series', '0004_auto_20200508_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatortoseries',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='creatortoseries',
            unique_together={('creator', 'series', 'number')},
        ),
    ]
