# Generated by Django 3.0.4 on 2020-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_auto_20200510_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='signature_fragment',
            field=models.CharField(default='NULL', max_length=64),
            preserve_default=False,
        ),
    ]
