# Generated by Django 3.0.4 on 2020-08-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
        ('series', '0005_series_book_code_sortable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatortoseries',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creators.Creator'),
        ),
        migrations.AlterField(
            model_name='creatortoseries',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creators.CreatorRole'),
        ),
    ]
