# Generated by Django 3.0.4 on 2020-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_auto_20200805_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesnode',
            name='old_id',
            field=models.IntegerField(null=True),
        ),
    ]
