# Generated by Django 3.0.4 on 2020-07-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_series_signature_fragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinseries',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
