# Generated by Django 3.2.10 on 2022-05-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
        ('creators', '0002_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='TITLE', max_length=8)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.publication')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.searchword')),
            ],
        ),
        migrations.CreateModel(
            name='SubWorkWordMatch',
            fields=[
                ('wordmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.wordmatch')),
                ('sub_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.subwork')),
            ],
            bases=('search.wordmatch',),
        ),
        migrations.CreateModel(
            name='SeriesWordMatch',
            fields=[
                ('wordmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.wordmatch')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.series')),
            ],
            bases=('search.wordmatch',),
        ),
        migrations.CreateModel(
            name='AuthorWordMatch',
            fields=[
                ('wordmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.wordmatch')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.creator')),
            ],
            bases=('search.wordmatch',),
        ),
    ]
