# Generated by Django 3.2.22 on 2024-02-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchword',
            name='word',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wordmatch',
            name='type',
            field=models.CharField(db_index=True, default='TITLE', max_length=8),
        ),
    ]
