# Generated by Django 3.1.5 on 2021-08-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorWordMatch',
            fields=[
                ('wordmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.wordmatch')),
            ],
            bases=('search.wordmatch',),
        ),
    ]
