# Generated by Django 5.2.3 on 2025-07-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20240228_1941'),
        ('works', '0003_alter_item_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmatch',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
