# Generated by Django 5.2.6 on 2025-10-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20240228_1941'),
        ('works', '0005_subwork_datamigrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkwordmatch',
            name='sub_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
