# Generated by Django 5.1.4 on 2025-03-01 18:16
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_initial'),
        ('search', '0002_auto_20240228_1941'),
        ('series', '0001_initial'),
        ('works', '0002_rename_datetime_itemstate_date_time'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
    ]
