# Generated by Django 5.2.3 on 2025-10-02 14:28

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGistExtension, BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20240228_1941'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='searchword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['word'], name='search_sear_word_5468f9_gin'),
        ),
    ]
