# Generated by Django 3.1.5 on 2021-08-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_auto_20201203_2010'),
        ('search', '0002_authorwordmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorwordmatch',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creators.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordmatch',
            name='type',
            field=models.CharField(default='TITLE', max_length=8),
        ),
    ]
