# Generated by Django 5.2.3 on 2025-10-04 13:25

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20240228_1941'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='searchword',
            name='word',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='searchword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['word'], name='search_sear_word_5468f9_gin'),
        ),
    ]
