# Generated by Django 5.2.3 on 2025-11-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_searchword_word_and_more'),
        ('works', '0004_workrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmatch',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
