# Generated by Django 5.2.3 on 2025-07-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_wordmatch_publication'),
        ('works', '0004_alter_workinpublication_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkwordmatch',
            name='sub_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
