# Generated by Django 5.2.5 on 2025-10-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_searchword_word_and_more'),
        ('works', '0003_uppercase_existing_sortable_book_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmatch',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work'),
        ),
    ]
