# Generated by Django 5.2.6 on 2025-11-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_searchword_word_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubWorkWordMatch',
        ),
    ]
