# Generated by Django 3.1.5 on 2021-08-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20210801_1231'),
        ('search', '0004_serieswordmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubWorkWordMatch',
            fields=[
                ('wordmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.wordmatch')),
                ('sub_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.subwork')),
            ],
            bases=('search.wordmatch',),
        ),
    ]
