# Generated by Django 5.2.3 on 2025-11-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_wordmatch_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeriesWordMatch',
        ),
    ]
