# Generated by Django 5.1.1 on 2025-05-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_search_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmatch',
            name='word',
        ),
        migrations.RemoveField(
            model_name='serieswordmatch',
            name='series',
        ),
        migrations.RemoveField(
            model_name='serieswordmatch',
            name='wordmatch_ptr',
        ),
        migrations.RemoveField(
            model_name='subworkwordmatch',
            name='sub_work',
        ),
        migrations.RemoveField(
            model_name='subworkwordmatch',
            name='wordmatch_ptr',
        ),
        migrations.RemoveField(
            model_name='wordmatch',
            name='publication',
        ),
        migrations.DeleteModel(
            name='AuthorWordMatch',
        ),
        migrations.DeleteModel(
            name='SearchWord',
        ),
        migrations.DeleteModel(
            name='SeriesWordMatch',
        ),
        migrations.DeleteModel(
            name='SubWorkWordMatch',
        ),
        migrations.DeleteModel(
            name='WordMatch',
        ),
    ]
