# Generated by Django 5.2.3 on 2025-11-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_delete_subworkwordmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serieswordmatch',
            name='series',
        ),
        migrations.RemoveField(
            model_name='serieswordmatch',
            name='wordmatch_ptr',
        ),
        migrations.DeleteModel(
            name='AuthorWordMatch',
        ),
        migrations.DeleteModel(
            name='SeriesWordMatch',
        ),
    ]
