# Generated by Django 5.2.9 on 2026-01-02 20:31

import search.models.search_word
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_serieswordmatch_series_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchword',
            name='search_sear_word_5468f9_gin',
        ),
        migrations.AddIndex(
            model_name='searchword',
            index=search.models.search_word.TrigramIndex(fields=['word'], name='search_sear_word_5468f9_gin'),
        ),
    ]
