# Generated by Django 3.0.4 on 2020-08-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Member')),
            ],
        ),
    ]
