# Generated by Django 3.2.10 on 2022-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maillog',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
