# Generated by Django 4.2.15 on 2024-09-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20220624_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailLog',
        ),
    ]
