# Generated by Django 3.2.10 on 2022-05-02 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('active_member_committee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLineOne', models.CharField(max_length=255)),
                ('addressLineTwo', models.CharField(max_length=255)),
                ('addressLineThree', models.CharField(blank=True, max_length=255)),
                ('addressLineFour', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('student_number', models.CharField(blank=True, max_length=32)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_anonymous_user', models.BooleanField(default=False)),
                ('privacy_activities', models.BooleanField(default=False)),
                ('privacy_publications', models.BooleanField(default=False)),
                ('privacy_reunions', models.BooleanField(default=False)),
                ('privacy_reunion_end_date', models.DateField(auto_now=True)),
                ('invitation_code', models.CharField(blank=True, max_length=64, null=True)),
                ('invitation_code_valid', models.BooleanField(default=False)),
                ('dms_registered', models.BooleanField(default=False)),
                ('is_anonimysed', models.BooleanField(default=False)),
                ('committees', models.ManyToManyField(blank=True, to='members.Committee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('committee_update', 'Can update committee')],
            },
        ),
        migrations.CreateModel(
            name='MemberBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('visual_name', models.CharField(max_length=64)),
                ('old_str', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('visual_name', models.CharField(max_length=64)),
                ('old_str', models.CharField(blank=True, max_length=64, null=True)),
                ('needs_union_card', models.BooleanField(default=True)),
                ('has_end_date', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member')),
                ('member_background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.memberbackground')),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.membershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLineOne', models.CharField(max_length=255)),
                ('addressLineTwo', models.CharField(max_length=255)),
                ('addressLineThree', models.CharField(blank=True, max_length=255)),
                ('addressLineFour', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('student_number', models.CharField(blank=True, max_length=32)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
