# Generated by Django 3.0.3 on 2020-03-04 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLineOne', models.CharField(max_length=255)),
                ('addressLineTwo', models.CharField(max_length=255)),
                ('addressLineThree', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('student_number', models.CharField(max_length=32)),
                ('membership_type_old', models.CharField(max_length=32)),
                ('notes', models.CharField(max_length=1023)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('is_anonymous_user', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
