# Generated by Django 3.0.3 on 2020-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('addressLineOne', models.CharField(max_length=255)),
                ('addressLineTwo', models.CharField(max_length=255)),
                ('addressLineThree', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('student_number', models.CharField(max_length=32)),
                ('membership_type_old', models.CharField(max_length=32)),
                ('notes', models.CharField(max_length=1023)),
                ('old_customer_type', models.CharField(max_length=64)),
                ('old_id', models.IntegerField()),
                ('is_anonymous_user', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
