# Generated by Django 3.0.3 on 2020-03-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='old_customer_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
