# Generated by Django 3.0.4 on 2020-08-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('visual_name', models.CharField(max_length=64)),
                ('old_str', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('visual_name', models.CharField(max_length=64)),
                ('old_str', models.CharField(max_length=64)),
                ('needs_union_card', models.BooleanField(default=True)),
                ('has_end_date', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLineOne', models.CharField(max_length=255)),
                ('addressLineTwo', models.CharField(max_length=255)),
                ('addressLineThree', models.CharField(blank=True, max_length=255)),
                ('addressLineFour', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('student_number', models.CharField(max_length=32)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('member_background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.MemberBackground')),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.MembershipType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='member_background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.MemberBackground'),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.MembershipType'),
        ),
    ]
