# Generated by Django 3.2.13 on 2023-10-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='addresslinefour',
            new_name='address_line_four',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='addresslineone',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='addresslinethree',
            new_name='address_line_three',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='addresslinetwo',
            new_name='address_line_two',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addresslinefour',
            new_name='address_line_four',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addresslineone',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addresslinethree',
            new_name='address_line_three',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addresslinetwo',
            new_name='address_line_two',
        ),
    ]
