# Generated by Django 3.0.3 on 2020-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='studentNumber',
            new_name='student_number',
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type_old',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='old_customer_type',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='old_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
