# Generated by Django 3.0.7 on 2020-07-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(),
        ),
    ]
