# Generated by Django 3.0.4 on 2020-07-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
