# Generated by Django 3.2.13 on 2023-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invitation_code_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
