# Generated by Django 3.0.4 on 2020-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invitation_code_valid',
            field=models.BooleanField(default=False),
        ),
    ]
