# Generated by Django 3.2.13 on 2023-10-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20231003_1513'),
        ('members', '0002_member_invitation_code_end_date'),
    ]

    operations = [
    ]
