# Generated by Django 3.2.13 on 2023-10-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_invitation_code_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='addressLineFour',
            new_name='address_line_four',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='addressLineOne',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='addressLineThree',
            new_name='address_line_three',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='addressLineTwo',
            new_name='address_line_two',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addressLineFour',
            new_name='address_line_four',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addressLineOne',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addressLineThree',
            new_name='address_line_three',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='addressLineTwo',
            new_name='address_line_two',
        ),
    ]
