# Generated by Django 3.0.3 on 2020-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200219_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_anonymous_user',
            field=models.BooleanField(default=False),
        ),
    ]
