# Generated by Django 3.0.4 on 2020-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200818_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='memberlog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberlog',
            name='student_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
