# Generated by Django 3.0.4 on 2020-07-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200703_0933'),
        ('members', '0002_auto_20200704_1423'),
    ]

    operations = [
    ]
