# Generated by Django 3.1.1 on 2020-12-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200912_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(default='2020-09-01', null=True),
        ),
        migrations.AddField(
            model_name='memberlog',
            name='start_date',
            field=models.DateField(default='2020-09-01', null=True),
        ),
    ]
