# Generated by Django 3.0.4 on 2020-08-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_invitation_code_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLineOne', models.CharField(max_length=255)),
                ('addressLineTwo', models.CharField(max_length=255)),
                ('addressLineThree', models.CharField(blank=True, max_length=255)),
                ('addressLineFour', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('student_number', models.CharField(max_length=32)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
