# Generated by Django 4.2.14 on 2024-07-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20231012_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='primary_email',
        ),
        migrations.RenameField(
            model_name='memberlog',
            old_name='email',
            new_name='primary_email',
        ),
        migrations.AddField(
            model_name='member',
            name='primary_email_in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='secondary_email_in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberlog',
            name='primary_email_in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberlog',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberlog',
            name='secondary_email_in_use',
            field=models.BooleanField(default=False),
        ),
    ]
