# Generated by Django 3.0.3 on 2020-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_anonymous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='end_date',
            field=models.DateField(default="2020-01-01"),
            preserve_default=False,
        ),
    ]
