# Generated by Django 3.0.3 on 2020-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200304_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('active_member_committee', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='committees',
            field=models.ManyToManyField(to='members.Committee'),
        ),
    ]
