# Generated by Django 3.0.4 on 2020-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_merge_20200704_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='addressLineFour',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='addressLineThree',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
