# Generated by Django 3.1.1 on 2020-12-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20201224_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2020-09-01', null=True)),
                ('end_date', models.DateField(default='2021-06-30', null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
    ]
