# Generated by Django 3.1.1 on 2020-12-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membershipperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipperiod',
            name='member_background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.memberbackground'),
        ),
        migrations.AddField(
            model_name='membershipperiod',
            name='membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.membershiptype'),
        ),
    ]
