# Generated by Django 3.1.1 on 2020-12-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_fill_membershipperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_background',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='memberlog',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='memberlog',
            name='member_background',
        ),
        migrations.RemoveField(
            model_name='memberlog',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='memberlog',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='membershipperiod',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membershipperiod',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
