# Generated by Django 3.2.4 on 2021-06-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20201224_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dms_registered',
            field=models.BooleanField(default=False),
        ),
    ]
