# Generated by Django 3.1.7 on 2021-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210604_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
