# Generated by Django 3.2.10 on 2022-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_membershipperiod_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberbackground',
            name='old_str',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='old_str',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
