# Generated by Django 3.2.10 on 2022-04-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20211002_1144'),
        ('members', '0011_auto_20220407_1606'),
    ]

    operations = [
    ]
