# Generated by Django 3.2.10 on 2022-04-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20220407_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership_type_old',
        ),
        migrations.RemoveField(
            model_name='member',
            name='old_customer_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='old_id',
        ),
    ]
