# Generated by Django 3.2.10 on 2022-04-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20220409_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlog',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
    ]
