# Generated by Django 3.0.4 on 2020-07-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_names', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('old_id', models.IntegerField()),
                ('is_alias_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='works.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('article', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('old_id', models.IntegerField()),
                ('signature', models.CharField(max_length=64)),
                ('signature_extension', models.CharField(max_length=64)),
                ('isbn10', models.CharField(blank=True, max_length=64, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=64, null=True)),
                ('pages', models.CharField(blank=True, max_length=32, null=True)),
                ('hidden', models.BooleanField()),
                ('comment', models.TextField(default='')),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('bought_date', models.DateField(default='1900-01-01')),
                ('added_on', models.DateField(auto_now_add=True)),
                ('last_seen', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('old_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('article', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(blank=True, max_length=64, null=True)),
                ('original_article', models.CharField(blank=True, max_length=64, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('is_translated', models.BooleanField()),
                ('date_added', models.DateField()),
                ('sorting', models.CharField(choices=[('AUTHOR', 'Author'), ('TITLE', 'Title')], default='TITLE', max_length=64)),
                ('comment', models.TextField()),
                ('internal_comment', models.CharField(max_length=1024)),
                ('signature_fragment', models.CharField(max_length=64)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('hidden', models.BooleanField()),
                ('listed_author', models.CharField(default='ZZZZZZZZ', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.Work')),
            ],
            options={
                'abstract': False,
            },
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='SubWork',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.Work')),
            ],
            options={
                'abstract': False,
            },
            bases=('works.work', models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_id', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('AVAILABLE', 'Available'), ('MISSING', 'Missing'), ('LOST', 'Lost'), ('BROKEN', 'Broken')], max_length=64)),
                ('reason', models.TextField()),
                ('inventarisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarisation.Inventarisation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='works.Location'),
        ),
        migrations.AddField(
            model_name='category',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.ItemType'),
        ),
        migrations.CreateModel(
            name='WorkInPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_publication', models.IntegerField()),
                ('display_number_in_publication', models.CharField(max_length=64)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Publication')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.SubWork')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Publication'),
        ),
        migrations.CreateModel(
            name='CreatorToWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Creator')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.CreatorRole')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Work')),
            ],
            options={
                'unique_together': {('creator', 'work', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CreatorToItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Creator')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Item')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.CreatorRole')),
            ],
            options={
                'unique_together': {('creator', 'item', 'number')},
            },
        ),
    ]
