# Generated by Django 3.0.4 on 2020-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='item',
            name='signature_extension',
        ),
        migrations.RemoveField(
            model_name='work',
            name='signature_fragment',
        ),
        migrations.AddField(
            model_name='creator',
            name='identifying_code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='book_code',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='code_extension',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='location',
            name='sig_gen',
            field=models.CharField(choices=[('Author', 'author'), ('Author_Translated', 'author_translated'), ('Title', 'title')], default='author', max_length=64),
        ),
        migrations.AddField(
            model_name='work',
            name='book_code',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='code_extension',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='bought_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
