# Generated by Django 3.0.4 on 2020-04-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('AVAILABLE', 'Available'), ('MISSING', 'Missing'), ('LOST', 'Lost'), ('BROKEN', 'Broken')], max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Item')),
            ],
        ),
    ]
