# Generated by Django 3.0.3 on 2020-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='original_subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='original_title',
            field=models.CharField(max_length=255),
        ),
    ]
