# Generated by Django 3.0.4 on 2020-08-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book_code_extension',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='old_id',
            field=models.IntegerField(null=True),
        ),
    ]
