# Generated by Django 3.2.13 on 2023-10-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemstate',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
