# Generated by Django 3.0.3 on 2020-02-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='work',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='work',
            name='language',
        ),
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='isbn',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CreatorToItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Creator')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Item')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.CreatorRole')),
            ],
        ),
    ]
