# Generated by Django 5.1.4 on 2025-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_rename_datetime_itemstate_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='searchmake_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='searchmake_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
