# Generated by Django 3.2.13 on 2023-10-03 15:13

from django.db import migrations

from works.models import Item


def forwards_func(apps, schema_editor):
    for item in Item.objects.all():
        item.book_code_sortable = item.book_code_sortable.upper()
        item.save()
class Migration(migrations.Migration):
    dependencies = [
        ('works', '0002_rename_datetime_itemstate_date_time'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
