# Generated by Django 3.0.3 on 2020-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200216_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinpublication',
            name='display_number_in_work',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
