# Generated by Django 3.2.24 on 2024-02-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_rename_datetime_itemstate_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstate',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
