# Generated by Django 3.0.3 on 2020-02-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200320_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('old_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='is_abc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='old_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='works.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('is_abc', 'code')},
        ),
        migrations.AddField(
            model_name='category',
            name='item_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='works.ItemType'),
            preserve_default=False,
        ),
    ]
