# Generated by Django 5.2.3 on 2025-07-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_rename_datetime_itemstate_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.work'),
        ),
    ]
