# Generated by Django 3.2.13 on 2023-10-03 15:13

from django.db import migrations

from book_code_generation.helpers import standardize_code
from works.models import Item


def forwards_func(apps, schema_editor):
    """
    This is a data-migration where we set all the "sortable book codes" to be fully upper cased. This allows our search to find them in a more adequate way.
    This migration may take some time (tm) because it's implemented in a fairly naive (but very straightforward) way.
    """
    for item in Item.objects.all():
        item.book_code_sortable = standardize_code(item.book_code).upper()
        item.save()
class Migration(migrations.Migration):
    dependencies = [
        ('works', '0002_rename_datetime_itemstate_date_time'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
