# Generated by Django 3.0.4 on 2020-08-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200730_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='signature_fragment',
        ),
    ]
