# Generated by Django 3.0.4 on 2020-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200806_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book_code_extension',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
