# Generated by Django 3.0.4 on 2020-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_itemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstate',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
