# Generated by Django 3.0.3 on 2020-02-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200219_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatortowork',
            name='old_id',
        ),
    ]
