# Generated by Django 5.1.4 on 2025-03-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_item_searchmake_words_work_searchmake_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='searchmake_words',
            new_name='search_words',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='searchmake_words',
            new_name='search_words',
        ),
    ]
