# Generated by Django 5.2.6 on 2025-10-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_uppercase_existing_sortable_book_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_relation', models.IntegerField()),
                ('display_number_in_relation', models.CharField(max_length=64)),
                ('relation_type', models.IntegerField(choices=[(1, 'Sub Work'), (2, 'Series')])),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='works.work')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
        ),
    ]
