# Generated by Django 3.0.3 on 2020-02-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_workinpublication_display_number_in_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinpublication',
            old_name='display_number_in_work',
            new_name='display_number_in_publication',
        ),
        migrations.RenameField(
            model_name='workinpublication',
            old_name='number_in_work',
            new_name='number_in_publication',
        ),
        migrations.RenameField(
            model_name='workinpublication',
            old_name='item',
            new_name='publication',
        ),
    ]
