# Generated by Django 3.0.4 on 2020-09-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200912_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='book_code',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='book_code_sortable',
        ),
    ]
