# Generated by Django 5.2.3 on 2025-07-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_wordmatch_publication'),
        ('works', '0003_alter_item_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='works.work'),
        ),
        migrations.AlterField(
            model_name='workinpublication',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subwork', to='works.subwork'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
