# Generated by Django 3.0.4 on 2020-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_itemstate_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='given_names',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatortoitem',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatortowork',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='creatortoitem',
            unique_together={('creator', 'item', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='creatortowork',
            unique_together={('creator', 'work', 'number')},
        ),
    ]
