# Generated by Django 3.0.4 on 2020-04-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarisation', '0001_initial'),
        ('works', '0003_itemstate_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstate',
            name='inventarisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarisation.Inventarisation'),
        ),
    ]
