# Generated by Django 3.2.24 on 2024-05-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_itemstate_is_latest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('change_item_state', 'Change the state of an item'),)},
        ),
        migrations.RemoveField(
            model_name='itemstate',
            name='is_latest',
        ),
    ]
