# Generated by Django 5.2.3 on 2025-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_uppercase_existing_sortable_book_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book_code_sortable',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
