# Generated by Django 3.0.4 on 2020-07-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200730_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='book_code',
        ),
        migrations.RemoveField(
            model_name='work',
            name='book_code_extension',
        ),
        migrations.AddField(
            model_name='publication',
            name='book_code',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='book_code_extension',
            field=models.CharField(max_length=16),
        ),
    ]
