# Generated by Django 5.2.3 on 2025-10-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_uppercase_existing_sortable_book_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_index', models.IntegerField()),
                ('relation_index_label', models.CharField(max_length=64)),
                ('relation_kind', models.IntegerField(choices=[(1, 'Sub Work Of'), (2, 'Part Of Series')], db_index=True)),
                ('from_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='works.work')),
                ('to_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='works.work')),
            ],
        ),
    ]
