# Generated by Django 3.0.3 on 2020-02-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200225_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='old_number',
            new_name='old_id',
        ),
    ]
