# Generated by Django 5.2.3 on 2025-11-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_workseries'),
        ('works', '0004_workrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='based_on_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='series.series', unique=True),
        ),
    ]
