# Generated by Django 5.2.3 on 2025-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_item_book_code_sortable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book_code_sortable',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
