# Generated by Django 5.2.3 on 2025-07-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_workinpublication_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinpublication',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_works_publications', to='works.work'),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='publication',
            new_name='work',
        ),
        migrations.AlterField(
            model_name='workinpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_works_publications', to='works.work'),
        ),
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_publication', models.IntegerField()),
                ('display_number_in_publication', models.CharField(max_length=64)),
                ('type', models.CharField(default='SUBWORK', max_length=32)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_child_set', to='works.work')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_parent_set', to='works.work')),
            ],
        ),
        migrations.DeleteModel(
            name='SubWork',
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO works_workrelation(number_in_publication, display_number_in_publication, child_id, parent_id, type) SELECT number_in_publication, display_number_in_publication, work_id, publication_id, 'SUBWORK' from works_workinpublication
            """
        ),
        migrations.DeleteModel(
            name='WorkInPublication',
        ),
    ]
