# Generated by Django 3.0.7 on 2021-08-11 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstate',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='itemstate',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemstate',
            name='type',
            field=models.CharField(
                choices=[('AVAILABLE', 'Available'), ('MISSING', 'Missing'), ('LOST', 'Lost'), ('BROKEN', 'Broken'), ('OFFSITE', 'Off-Site'), ('DISPLAY', 'On Display'), ('FEATURED', 'Featured'),
                         ('SOLD', 'Sold'), ('FORSALE', 'For Sale')], max_length=64),
        ),
    ]
