# Generated by Django 3.0.3 on 2020-03-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200225_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_abc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='old_id',
        ),
    ]
