# Generated by Django 5.2.6 on 2025-10-19 11:23

import django.db.models.deletion
from django.db import migrations, models

from works.models import WorkRelation, Work


sql_migrate = """
INSERT INTO works_workrelation(relates_to_id, work_id, display_number_in_relation, number_in_relation, relation_type)
SELECT publication_id, work_id, display_number_in_publication, number_in_publication, 1
FROM works_workinpublication
"""


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_workrelation'),
    ]

    operations = [
        migrations.RunSQL(sql_migrate),
    ]
