# Generated by Django 5.2.3 on 2025-11-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_wordmatch_publication'),
        ('works', '0004_workrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_in_publication_root', to='works.work'),
        ),
        migrations.AlterField(
            model_name='item',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.work'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
