# Generated by Django 3.2.10 on 2022-03-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20210801_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='old_id',
            field=models.IntegerField(null=True),
        ),
    ]
