# Generated by Django 5.2.3 on 2025-11-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_workinpublication_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrelation',
            name='relation_index',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
