# Generated by Django 3.0.4 on 2020-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_listed_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='listed_author',
            field=models.CharField(default='ZZZZZZZZ', max_length=64),
        ),
    ]
