# Generated by Django 5.2.3 on 2025-11-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_seriesv2'),
        ('works', '0005_alter_workinpublication_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='based_on_series',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='series.series'),
        ),
    ]
