# Generated by Django 3.0.4 on 2020-08-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
        ('series', '0006_auto_20200805_1045'),
        ('works', '0005_auto_20200803_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatortoitem',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creators.Creator'),
        ),
        migrations.AlterField(
            model_name='creatortoitem',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creators.CreatorRole'),
        ),
        migrations.AlterField(
            model_name='creatortowork',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creators.Creator'),
        ),
        migrations.AlterField(
            model_name='creatortowork',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creators.CreatorRole'),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='CreatorRole',
        ),
    ]
