# Generated by Django 5.2.6 on 2025-10-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_subwork_datamigrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinpublication',
            name='work',
        ),
        migrations.RemoveField(
            model_name='workinpublication',
            name='publication',
        ),
        migrations.DeleteModel(
            name='SubWork',
        ),
        migrations.DeleteModel(
            name='WorkInPublication',
        ),
    ]
