# Generated by Django 3.0.7 on 2021-08-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20210811_1705'),
        ('works', '0002_auto_20200819_1459'),
    ]

    operations = [
    ]
