# Generated by Django 3.0.4 on 2020-05-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_listed_author'),
        ('works', '0004_itemstate_inventarisation'),
    ]

    operations = [
    ]
