# Generated by Django 5.2.3 on 2025-11-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_work_based_on_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='based_on_series',
        ),
    ]
