# Generated by Django 3.0.7 on 2021-08-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_merge_20210811_1713'),
        ('works', '0005_auto_20210801_1231'),
    ]

    operations = [
    ]
