# Generated by Django 3.0.3 on 2020-03-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_location_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='works.Location'),
        ),
    ]
