# Generated by Django 3.0.7 on 2020-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20200702_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(),
        ),
    ]
