# Generated by Django 3.0.4 on 2020-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20200805_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='internal_comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
