# Generated by Django 5.2.3 on 2025-11-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_delete_subworkwordmatch'),
        ('works', '0006_subwork_datamigrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinpublication',
            name='work',
        ),
        migrations.RemoveField(
            model_name='workinpublication',
            name='publication',
        ),
        migrations.DeleteModel(
            name='SubWork',
        ),
        migrations.DeleteModel(
            name='WorkInPublication',
        ),
    ]
