# Generated by Django 3.0.4 on 2020-08-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20200805_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatorToItem',
        ),
    ]
