# Generated by Django 3.0.4 on 2020-07-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20200703_0903'),
        ('works', '0006_merge_20200525_1754'),
    ]

    operations = [
    ]
