# Generated by Django 3.0.4 on 2020-07-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_merge_20200704_1506'),
        ('works', '0006_auto_20200704_1423'),
    ]

    operations = [
    ]
