# Generated by Django 3.0.4 on 2020-07-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_merge_20200704_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sig_gen',
            field=models.CharField(choices=[('Author', 'author'), ('Author_Translated', 'author_translated'), ('Title', 'title')], default='author', max_length=64),
        ),
    ]
