# Generated by Django 5.2.3 on 2025-11-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_remove_workinpublication_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrelation',
            name='relation_index_label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
