# Generated by Django 5.2.3 on 2025-11-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_seriesv2'),
        ('works', '0009_alter_workrelation_relation_index_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrelation',
            name='relation_index',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='based_on_series',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='series.series'),
        ),
    ]
