# Generated by Django 3.0.3 on 2020-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_merge_20200704_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bought_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='signature_extension',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
