# Generated by Django 3.0.4 on 2020-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_merge_20200704_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pages',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
