# Generated by Django 5.2.3 on 2025-11-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_work_based_on_series'),
        ('series', '0003_workseries_datamigrate')
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='based_on_series',
        ),
    ]
