# Generated by Django 5.2.9 on 2026-01-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_remove_work_based_on_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book_code_extension',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
